//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practik.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int sku { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string manufacturer { get; set; }
        public string description { get; set; }
        public string short_description { get; set; }
        public string product_url { get; set; }
    }
}
